//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaMedW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphic
    {
        public int Id { get; set; }
        public int PersonalId { get; set; }
        public System.DateTime Dt { get; set; }
        public int H1 { get; set; }
        public int M1 { get; set; }
        public int H2 { get; set; }
        public int M2 { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
