//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaMedW
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        public string BenefitName { get; set; }
        public int Kol { get; set; }
        public decimal Price { get; set; }
        public decimal Sm { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
