//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaMedW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaaMedEntities : DbContext
    {
        public SaaMedEntities()
            : base("name=SaaMedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
    }
}
