//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaMedW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaaMedEntities : DbContext
    {
        public SaaMedEntities()
            : base("name=SaaMedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Graphic> Graphic { get; set; }
        public virtual DbSet<Benefit> Benefit { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
        public virtual DbSet<VisitBenefit> VisitBenefit { get; set; }
        public virtual DbSet<PersonalSpecialty> PersonalSpecialty { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<MKB> MKB { get; set; }
    }
}
