//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaMedW
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitBenefit
    {
        public int Id { get; set; }
        public int VisitId { get; set; }
        public int BenefitId { get; set; }
        public int Status { get; set; }
        public int Kol { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
